/**
 * Promptfoo Integration Helper for AIQualityHQ
 * Generates promptfooconfig.yaml for automated LLM testing & benchmarking
 */

export interface PromptfooConfigOptions {
  title?: string;
  description?: string;
  useCase?: string;
  score?: number;
}

/**
 * Generates a valid promptfooconfig.yaml configuration string from prompt text
 */
export function generatePromptfooConfig(
  promptText: string,
  options: PromptfooConfigOptions = {}
): string {
  const safeTitle = options.title || 'AIQualityHQ Evaluated Prompt';
  const safeDescription =
    options.description || 'Automated multi-model benchmark generated by AIQualityHQ';
  
  // Format multi-line prompt text cleanly into YAML block format
  const indentedPrompt = promptText
    .split('\n')
    .map((line) => `    ${line}`)
    .join('\n');

  return `# ==============================================================================
# Promptfoo Configuration
# Generated by AIQualityHQ (https://aiqualityhq.com)
# Date: ${new Date().toISOString().split('T')[0]}
# Prompt Score: ${options.score ? `${options.score}/100` : 'N/A'}
# ==============================================================================

description: "${safeTitle} - ${safeDescription}"

prompts:
  - |
${indentedPrompt}

# Target LLM Providers to test against
providers:
  - id: openai:gpt-4o
    config:
      temperature: 0.7
      max_tokens: 1000
  - id: anthropic:messages:claude-3-5-sonnet-20241022
    config:
      temperature: 0.7
      max_tokens: 1000
  - id: google:gemini-1.5-pro
    config:
      temperature: 0.7

# Default assertions across all test cases
defaultTest:
  assert:
    - type: latency
      threshold: 5000 # Max response time 5000ms
    - type: cost
      threshold: 0.05 # Max cost per request $0.05

# Test cases with input variables (if prompt contains {{variables}})
tests:
  - description: "Standard evaluation scenario"
    vars:
      input: "Demonstration input query"
    assert:
      - type: is-json # Example assertion: change based on your expected output
        options:
          required: []
      - type: llm-rubric
        value: "The response is helpful, clear, and directly answers the query without hallucinations."

# Quick Run Instructions:
# 1. Install promptfoo: npm install -g promptfoo
# 2. Set your API keys: export OPENAI_API_KEY="your-key"
# 3. Run evaluation: promptfoo eval -c promptfooconfig.yaml
# 4. View results web UI: promptfoo view
`;
}

/**
 * Trigger browser download for promptfooconfig.yaml
 */
export function downloadPromptfooConfig(
  yamlContent: string,
  filename: string = 'promptfooconfig.yaml'
): void {
  const blob = new Blob([yamlContent], { type: 'text/yaml;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
